name: CI Suite

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run_tests:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Run Tests
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Rustfmt
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo test --all-features
